# This is a manually triggered workflow which can be triggered from Github
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
#
# Run this workflow after TypeScript has created a new release
# If there is a new TypeScript release, this workflow will rebase
# our changes to TypeScript on top of this new version of TypeScript
name: New TS release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
        ref: midgard
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Fetch upstream TypeScript
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://github.com/microsoft/TypeScript.git
        git fetch upstream
        ./scripts/midgard/update_fork.sh

